/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Tugas.AplikasiKonversiSuhu;

import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author USER
 */
public class FormKonversiSuhu extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public FormKonversiSuhu() {
        initComponents();
        buttonGroup1.add(Fahrenheit);
        buttonGroup1.add(Reamur);
        buttonGroup1.add(Kelvin);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtInput = new javax.swing.JTextField();
        cbSkala = new javax.swing.JComboBox<>();
        Fahrenheit = new javax.swing.JRadioButton();
        btnKonversi = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        Reamur = new javax.swing.JRadioButton();
        Kelvin = new javax.swing.JRadioButton();
        txtOutput = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Aplikasi Konversi Suhu");

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Masukkan Nilai Celcius :");

        txtInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtInputActionPerformed(evt);
            }
        });
        txtInput.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtInputKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtInputKeyTyped(evt);
            }
        });

        cbSkala.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-Pilih-", "Celcius ke Fahrenheit", "Celcius ke Kelvin", "Celcius ke Reamur", "Fahrenheit ke Celcius", "Kelvin ke Celcius", "Reamur ke Celcius" }));
        cbSkala.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbSkalaActionPerformed(evt);
            }
        });

        Fahrenheit.setForeground(new java.awt.Color(255, 255, 255));
        Fahrenheit.setText("Fahrenheit");
        Fahrenheit.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                FahrenheitItemStateChanged(evt);
            }
        });
        Fahrenheit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FahrenheitActionPerformed(evt);
            }
        });

        btnKonversi.setBackground(new java.awt.Color(102, 102, 102));
        btnKonversi.setForeground(new java.awt.Color(255, 255, 255));
        btnKonversi.setText("Konversi");
        btnKonversi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKonversiActionPerformed(evt);
            }
        });
        btnKonversi.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                btnKonversiKeyTyped(evt);
            }
        });

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Hasil :");

        Reamur.setForeground(new java.awt.Color(255, 255, 255));
        Reamur.setText("Reamur");
        Reamur.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                ReamurItemStateChanged(evt);
            }
        });
        Reamur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReamurActionPerformed(evt);
            }
        });

        Kelvin.setForeground(new java.awt.Color(255, 255, 255));
        Kelvin.setText("Kelvin");
        Kelvin.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                KelvinItemStateChanged(evt);
            }
        });
        Kelvin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KelvinActionPerformed(evt);
            }
        });

        txtOutput.setForeground(new java.awt.Color(255, 255, 255));
        txtOutput.setText("-");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(71, 71, 71)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(cbSkala, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(btnKonversi)
                                        .addGap(28, 28, 28))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(Fahrenheit)
                                        .addGap(18, 18, 18)
                                        .addComponent(Reamur))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel3))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtInput, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtOutput))))
                                .addGap(18, 18, 18)
                                .addComponent(Kelvin))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(107, 107, 107)
                        .addComponent(jLabel1)))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtOutput))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Fahrenheit)
                    .addComponent(Reamur)
                    .addComponent(Kelvin))
                .addGap(18, 18, 18)
                .addComponent(cbSkala, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnKonversi)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void FahrenheitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FahrenheitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FahrenheitActionPerformed

    private void ReamurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReamurActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ReamurActionPerformed
private double konversiSuhu(double nilai, String jenis) {
        return switch (jenis) {
            case "Celcius ke Fahrenheit" -> (nilai * 9/5) + 32;
            case "Celcius ke Kelvin" -> nilai + 273.15;
            case "Celcius ke Reamur" -> nilai * 4/5;
            case "Fahrenheit ke Celcius" -> (nilai - 32) * 5/9;
            case "Kelvin ke Celcius" -> nilai - 273.15;
            case "Reamur ke Celcius" -> nilai * 5/4;
            default -> 0;
        };
}

    private void cbSkalaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbSkalaActionPerformed

    }//GEN-LAST:event_cbSkalaActionPerformed

    private void btnKonversiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKonversiActionPerformed
    if (cbSkala.getSelectedIndex() == 0) {
        JOptionPane.showMessageDialog(this, "Silakan pilih jenis konversi terlebih dahulu.", "Peringatan", JOptionPane.WARNING_MESSAGE);
        return;
    }
    try {
        double input = Double.parseDouble(txtInput.getText());
        String jenis = cbSkala.getSelectedItem().toString();
        double hasil = konversiSuhu(input, jenis);
        txtOutput.setText(String.format("%.2f", hasil));
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Masukkan angka yang valid!", "Error", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_btnKonversiActionPerformed

    private void txtInputKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtInputKeyTyped
    char c = evt.getKeyChar();
    if (!Character.isDigit(c) && c != '.' && c != KeyEvent.VK_BACK_SPACE) {
        evt.consume(); // Hentikan input non-angka
        Toolkit.getDefaultToolkit().beep();
    }
    }//GEN-LAST:event_txtInputKeyTyped

    private void btnKonversiKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnKonversiKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_btnKonversiKeyTyped

    private void FahrenheitItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_FahrenheitItemStateChanged
    if (Fahrenheit.isSelected()) {
        cbSkala.setSelectedItem("Celcius ke Fahrenheit");
    }
    }//GEN-LAST:event_FahrenheitItemStateChanged

    private void txtInputKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtInputKeyReleased
    if (!txtInput.getText().isEmpty()) {
        try {
            double input = Double.parseDouble(txtInput.getText());
            String jenis = cbSkala.getSelectedItem().toString();
            double hasil = konversiSuhu(input, jenis);
            txtOutput.setText(String.format("%.2f", hasil));
        } catch (NumberFormatException e) {
            txtOutput.setText("Input tidak valid");
        }
    }
    }//GEN-LAST:event_txtInputKeyReleased

    private void txtInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtInputActionPerformed

    private void KelvinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KelvinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_KelvinActionPerformed

    private void ReamurItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_ReamurItemStateChanged
    if (Reamur.isSelected()) {
        cbSkala.setSelectedItem("Celcius ke Reamur");
    }
    }//GEN-LAST:event_ReamurItemStateChanged

    private void KelvinItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_KelvinItemStateChanged
    if (Kelvin.isSelected()) {
        cbSkala.setSelectedItem("Celcius ke Kelvin");
    }
    }//GEN-LAST:event_KelvinItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormKonversiSuhu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormKonversiSuhu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormKonversiSuhu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormKonversiSuhu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormKonversiSuhu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton Fahrenheit;
    private javax.swing.JRadioButton Kelvin;
    private javax.swing.JRadioButton Reamur;
    private javax.swing.JButton btnKonversi;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.JComboBox<String> cbSkala;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtInput;
    private javax.swing.JLabel txtOutput;
    // End of variables declaration//GEN-END:variables
}
